<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StayPilot.Domain\StayPilot.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="DTOs\AiDtos\" />
    <Folder Include="DTOs\ContactDtos\" />
    <Folder Include="DTOs\BlogDtos\" />
    <Folder Include="DTOs\DestinationDtos\" />
    <Folder Include="DTOs\HeroDtos\" />
    <Folder Include="DTOs\HotelDtos\" />
    <Folder Include="DTOs\CurrencyDtos\" />
    <Folder Include="DTOs\WeatherDtos\" />
    <Folder Include="Mappings\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
